### ISSUE TITLE
Extract subcommand name from docstring (idea)

### ISSUE THREAD

**Issue by rob-smallshire** [abingham/docopt-subcommands#10]
I can't help but think that it would be more in the spirit of docopt to extract the subcommand name
from the docstring for a subcommand. For example, instead of:

```
@commands.command('report')
def report(args):
    """Usage: {program} {command} <filename>

    Print a human-readable report of the file contents.
    """
    filename = args['<filename>']
```

you could have,

```
@commands.command()
def report(args):
    """Usage: {program} report <filename>

    Print a human-readable report of the file contents.
    """
    filename = args['<filename>']
```

**Comment by abingham** [comment]
I like that a lot. The only issue that I can think of is that a user might want to register the same function under two different names (e.g. for backwards compatibility or something). But I guess that a name provided to the `command` decorator could override the name provided in the docstring; I think that would work.

We'd also need to decide if the command name in the docstring was *mandatory* (but overridable), or if we'd retain the current behavior. All said, though, I certainly agree that your proposal is very much in the spirit of docopt.

**Comment by abingham** [comment]
I've put some initial work into this in the [`subcommand-name-from-docstring` branch](https://github.com/abingham/docopt-subcommands/tree/subcommand-name-from-docstring). It needs a bit of work still, I think, but have a look and see if you think it's going in the right direction.

**Comment by abingham** [comment]
I've merged in the PR.
