### ISSUE TITLE
Getting hold of the top-level docstring

### ISSUE THREAD

**Issue by rob-smallshire** [abingham/docopt-subcommands#6]
I'd like to be able to assign the top-level docstring, once template substitution has been performed, to `__doc__` in the module in which I use docopt_subcommands.  This strings appears to be available from the `Subcommands.top_level_doc` property, but the subcommands instance itself is not readily available.

Currently the specification of the command structure (i.e. program, version, doc_template, common_options_handler, commands) and passing of command-arguments (argv) are done in a single call, but it would be useful if the former could be done at module-import time, and the latter done when the code is executed.

I think this mostly amounts to not having - or using - your main() function.

**Comment by abingham** [comment]
I *think* you can get what you want by using `Subcommands` directly and bypassing `main()` (which should be a fully-supported mode of operation):

```
sc = Subcommands(...)
docstring = sc.top_level_doc
. . . 
err_code = sc(sys.argv[:1])
sys.exit(err_code)
```

**Comment by abingham** [comment]
So this seems to work correctly:
```python
import docopt_subcommands
import sys


sc = docopt_subcommands.Subcommands('foo', '0.0.1')

@sc.command('llama')
def llama(args):
    """usage: {program} {command}

    Do it. You know you want to.
    """
    print('llama')
    return 0

print(sc.top_level_doc)

print('-' * 80)

err = sc(sys.argv[1:])
print(err)
```

But if that's not what you're looking for, maybe there's a hole in the API that we need to plug.

**Comment by rob-smallshire** [comment]
Yes, that's essentially, what I'm doing now.
